# Generated by Django 4.1.1 on 2022-09-16 23:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismi', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Xabar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Model', models.CharField(blank=True, max_length=200, null=True)),
                ('Joylashuv', models.CharField(blank=True, choices=[('Toshkent', 'Toshkent'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Samarkand', 'Samarkand'), ('Navoiy', 'Navoiy'), ('Andijon', 'Andijon'), ('Xorazm', 'Xorazm'), ('Buxoro', 'Buxoro'), ("Qoroqolg'iston", "Qoroqolg'iston"), ("Farg'ona", "Farg'ona"), ('Surxondaryo', 'Surxondaryo'), ('Sirdaryo', 'Sirdaryo'), ('Namangan', 'Namangan'), ('Jizzah', 'Jizzah')], max_length=50, null=True)),
                ('Yetkazib_berish', models.IntegerField(blank=True, default=0, null=True)),
                ('Oldindan_tulov', models.IntegerField(blank=True, default=0, null=True)),
                ('General_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('Kredit', models.CharField(blank=True, max_length=200, null=True)),
                ('Kerakli_hujjatlar', models.CharField(blank=True, max_length=200, null=True)),
                ('Raqam1', models.CharField(blank=True, default='+998 71 123 45 67', max_length=200, null=True)),
                ('Raqam2', models.CharField(blank=True, default='+998 71 123 45 67', max_length=200, null=True)),
                ('Kafolat', models.CharField(blank=True, default='12 oy', max_length=70, null=True)),
                ('OS_versiyasi_ishga_tushirilganda', models.CharField(blank=True, max_length=100, null=True)),
                ('SIM_kartalar_soni', models.IntegerField(blank=True, default='1', null=True)),
                ('SIM_karta_turi', models.CharField(blank=True, max_length=100, null=True)),
                ('Ogirligi', models.CharField(blank=True, max_length=100, null=True)),
                ('ulchamlari_WxHxD', models.CharField(blank=True, max_length=100, null=True)),
                ('rang', models.CharField(blank=True, max_length=100, null=True)),
                ('Diagonal', models.CharField(blank=True, max_length=100, null=True)),
                ('rasm_hajmi', models.CharField(blank=True, max_length=100, null=True)),
                ('Aspekt_nisbati', models.CharField(blank=True, max_length=100, null=True)),
                ('Ekranni_avtomatik_aylantirish', models.CharField(blank=True, max_length=100, null=True)),
                ('Asosiy_kameralar_soni', models.CharField(blank=True, max_length=100, null=True)),
                ('Asosiy_kameralarning_ulchamlari', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_flesh', models.CharField(blank=True, max_length=100, null=True)),
                ('Old_kamera', models.CharField(blank=True, max_length=100, null=True)),
                ('Audio', models.CharField(blank=True, max_length=100, null=True)),
                ('Standart', models.CharField(blank=True, max_length=100, null=True)),
                ('Interfeyslar', models.CharField(blank=True, max_length=100, null=True)),
                ('Geopozitsiyalash', models.CharField(blank=True, max_length=100, null=True)),
                ('Markaziy_protsessor', models.CharField(blank=True, max_length=100, null=True)),
                ('Protsessor_yadrolari_soni', models.CharField(blank=True, max_length=100, null=True)),
                ('video_protsessor', models.CharField(blank=True, max_length=100, null=True)),
                ('Urnatilgan_xotira', models.CharField(blank=True, max_length=100, null=True)),
                ('RAM', models.CharField(blank=True, max_length=100, null=True)),
                ('Karnay_urnatilgan_dinamik', models.CharField(blank=True, max_length=100, null=True)),
                ('Boshqaruv', models.CharField(blank=True, max_length=100, null=True)),
                ('Samolyot_rejimi', models.CharField(blank=True, max_length=100, null=True)),
                ('Sensorlar', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
