# Generated by Django 4.1.1 on 2022-09-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Chegirma_narxi_bilan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Narxi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
