# Generated by Django 4.1.1 on 2022-09-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_chegirma_narxi_bilan_product_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tirnalishga_chidamli_shisha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
