# Generated by Django 4.1.1 on 2022-09-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_tirnalishga_chidamli_shisha'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Batareya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Batareya_quvvati',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Zaryadlovchi_ulagichi_turi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
