# Generated by Django 4.1.1 on 2022-09-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_batareya_product_batareya_quvvati_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.AlterField(
            model_name='product',
            name='General_image',
            field=models.ImageField(blank=True, default='./static/images/f74f39dbc9b60954c926d72401adf1cc.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='./static/images/f74f39dbc9b60954c926d72401adf1cc.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='./static/images/f74f39dbc9b60954c926d72401adf1cc.jpg', null=True, upload_to=''),
        ),
    ]
