# Generated by Django 4.1.1 on 2022-09-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_general_image_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='General_image',
            field=models.ImageField(blank=True, default='./static/images/f74f39dbc9b60954c926d72401adf1cc.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='./static/images/f74f39dbc9b60954c926d72401adf1cc.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default='./static/images/f74f39dbc9b60954c926d72401adf1cc.jpg', null=True, upload_to=''),
        ),
    ]
