# Generated by Django 4.1.1 on 2022-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_general_image_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Chegirma_narxi_bilan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
